name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Restore CI Cache
        id: cache-dependencies
        uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-${{ hashFiles('**/scripts/build.ps1') }}
      - name: Build Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: pwsh -File ./scripts/build.ps1 -DependenciesOnly
        shell: pwsh
      - name: Build Project (Debug)
        run: pwsh -File ./scripts/build.ps1 -ProjectOnly
        shell: pwsh
      - name: Build Project (Release)
        run: pwsh -File ./scripts/build.ps1 -ProjectOnly -Release
        shell: pwsh
