name: Format

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  format:
    name: format
    runs-on: windows-latest
    steps:
      - name: Test Formatting
        run: pwsh -File ./scripts/format.ps1 -Test
        shell: pwsh
